### ISSUE TITLE
Basics assistance/personal ideas

### ISSUE THREAD

**Issue by Nashatok** [Servius/star-wars-vehicles-eu-pack#1]
First things first, I should let you know. I know next-to-nothing about coding in lua, so any tips/guides you could send my way would be great.

For example, the first ship I'd like to get fully operational is the fp_majestic. I'd add a pair of manned dual cannons on each side of the main, and two pilot-controlled cannons like the upsilon shuttle on the wings (low rof but high dmg against other cruisers). I think it'd add something new and cool to the addon. Should I copy/paste from IS or start from scratch?

**Comment by Servius** [comment]
Easiest to start from the IS and get it to a rough working version of the majestic. 

Here is a tutorial on how to extract an addon: 
https://steamcommunity.com/sharedfiles/filedetails/?id=431638110 

Instead of dragging onto the gmad.exe you can instead right click and click "Open With" and then path it to the exe. It would then convert any gma you double click on.

**Comment by Nashatok** [comment]
Thanks a ton for the advice, the Majestic is coming along fine! Though, every time I think it's ready for release, I find something new to make it even better! I'd assume this is a normal issue...? x3

Although, there is one particular aspect giving me trouble. When I try to use main (pilot) cannons, I get an error, as follows:

[ERROR] addons/star_wars_vehicles_episode_1_495762961/lua/entities/fighter_base.lua:534: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. FireWeapons - addons/star_wars_vehicles_episode_1_495762961/lua/entities/fighter_base.lua:534
    3. Think - addons/star_wars_vehicles_episode_1_495762961/lua/entities/fighter_base.lua:839
     4. unknown - addons/star_wars_vehicles_eu_pack_671171750/lua/entities/fp_majestic.lua:138

Any ideas? Current fp_majestic file should be in my fork.

**Comment by Servius** [comment]
You havent synced your local work to the git repo. 

> I find something new to make it even better! I'd assume this is a normal issue...? x3

And yes. This is normal haha

**Comment by Nashatok** [comment]
I think it's fixed (Actually took care of it a while ago). But as far as the Majestic goes, I think I'm going to leave it as it currently is. Will update patch to the final version when I get a chance.

This is mostly because I found a new ship to use as an anti-capital-ship: the MC90. The model has three large turbolasers on each side, which brings me to my latest issue. Is there a way to refine how far left/right the gunners can look without going into base code?

**Comment by Servius** [comment]
Youll just need to pull the lines from basecode to define that stuff.

**Comment by Nashatok** [comment]
Ah, okay. Base code as in Gmod, or as in SWV Episode 1?
